<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-15T17:25:58 IST" name="Default suite" finished-at="2025-08-15T17:26:14 IST" duration-ms="15966">
    <groups>
    </groups>
    <test started-at="2025-08-15T17:25:58 IST" name="Default test" finished-at="2025-08-15T17:26:14 IST" duration-ms="15966">
      <class name="contacts.TC_VT_001_Test">
        <test-method is-config="true" signature="reportCnfig()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:25:58 IST" name="reportCnfig" finished-at="2025-08-15T17:25:58 IST" duration-ms="532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportCnfig -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:25:58 IST" name="openBrowser" finished-at="2025-08-15T17:26:03 IST" duration-ms="4348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:26:03 IST" name="login" finished-at="2025-08-15T17:26:07 IST" duration-ms="4467" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="clickOnContacts()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:26:07 IST" name="clickOnContacts" finished-at="2025-08-15T17:26:07 IST" duration-ms="78" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at contacts.TC_VT_001_Test.clickOnContacts(TC_VT_001_Test.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnContacts -->
        <test-method is-config="true" signature="Logout()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:26:08 IST" name="Logout" finished-at="2025-08-15T17:26:14 IST" duration-ms="6180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:26:14 IST" name="closeBrowser" finished-at="2025-08-15T17:26:14 IST" duration-ms="448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="reportBackup()[pri:0, instance:contacts.TC_VT_001_Test@139982de]" started-at="2025-08-15T17:26:14 IST" name="reportBackup" finished-at="2025-08-15T17:26:16 IST" duration-ms="1300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportBackup -->
      </class> <!-- contacts.TC_VT_001_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
